### ISSUE TITLE
[Question] searching for deleted streams

### ISSUE THREAD

**Issue by slyfox99** [thecoder75/liveme-api#13]
I know if you have the VidID you can get streams that where deleted in the past. Does this still work? I tried to wait for alive stream to end and copied the vID and came back to capture stream and search came up empty. 

Maybe deleted streams are really deleted now??? I don't know. Posing the question to be researched, maybe.

**Comment by thecoder75** [comment]
If the stream has only been hidden its still possible to get the information on using the VideoID.  Once its deleted by the user or Live.me, then its gone and there's no way to get any details on it.

I have noticed at times that after a live stream ends it can take anywhere from 1 to 15 minutes before it becomes available as a replay and I'm not sure if the VideoID changes too or not on it.
