### ISSUE TITLE
getVideoInfo and getChatHistoryForVideo broken

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-api#8]
**Live.Me did a server update on 10-27-17 which broke or changed the API format.**

Need help to figure out the new request format.  Now the commands return:
```javascript
{
     "status": "400",
     "msg": "errora!",
     "data": []
}
```

Something changed on Live.Me servers regarding the API calls, need to figure out what changed or how to get it working again.

Unfortunately do to time constraints, I do not know when or even if I can get it working again.

[LiveMe Tools Issue #93](https://github.com/thecoder75/liveme-tools/issues/93) contains details on the app side of this issue.

**Comment by pustulated** [comment]
Looks like they emplemented some keys.
This is what the url's look like.
https://live.ksmobile.net/live/queryinfo?userid=1&videoid=00000000000000000000&area=&h5=1&vali=DxdQl6HTBmNKBxd
Running that url with or without a key in a curl request with a real videoid gives this as response. 
Disallowed Key Characters.
Or a 400 error like you shown above.

**Comment by thecoder75** [comment]
I was afraid they implemented authentication or something similar as I'm guessing between using the LiveMe Tools and other similar scripts and apps a lot of requests were getting made to their servers.

If it truly is some sort of authentication key then the command can no longer be used by this module or anything similar then.

**Comment by pustulated** [comment]
Those were my thoughts exactly. A lot of the other api calls still work, but who knows for how long. It is still possible to get lists of videos etc. Only issue is you can only get the the initial broadcast data such as views and other live info one time without finding an alternative route or parsing the website directly.

**Comment by thecoder75** [comment]
*Received this from test1234 on Discord:*

Request changed from **GET** to **POST**

This doesn't work anymore:
`https://live.ksmobile.net/live/queryinfo?videoid=$%7Bvid%7D`

Need to use `Content-Type: application/x-www-form-urlencoded`
New parameters:
    &h5=1
    &vali=lm* (4characters, l, 4 characters, m, anything)

```
POST /live/queryinfo HTTP/1.1
Host: live.ksmobile.net
Content-Type: application/x-www-form-urlencoded
videoid={vid}&h5=1&vali=1234l5678m
```

```
var request = require("request");

var options = { method: 'POST',
  url: 'https://live.ksmobile.net/live/queryinfo',
  headers: 
   { 'content-type': 'application/x-www-form-urlencoded'},
  form: { videoid: '${vid}', h5: '1', vali: '1234l5678m' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

**Comment by thecoder75** [comment]
Will try to update API module this weekend with fixes.  Will also test other API commands to see if they support POST methods as well or just the GET methods currently being used.

**Comment by zp** [comment]
```
const axios = require('axios');
axios.defaults.headers.common['d'] = '';
````

The api checks for an http request header that starts with 'd' to grant access, it can be empty as well, so it's a very quick and easy fix. 

`axios.defaults.headers.common['d'] = '';` will pass the http header to all requests made.

I'm already using it locally and allows searching by video id and gets chat msgs, without having to refactor any code.

**Comment by thecoder75** [comment]
Thanks for the fast fix @zp.  I've applied it to the code and verified it fixes the issues perfectly.
